version: '3.8'

services:
  ocr-service:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - REDIS_URL_OCR
      - REDIS_URL_CELERY
      - AWS_REGION
      - EXECUTION_QUEUE_URL
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    depends_on:
      - redis
    volumes:
      - ./:/app
      # - ~/.cache/huggingface:/root/.cache/huggingface
    command: uvicorn main:app --host 0.0.0.0 --port 8000 # --reload

  celery-worker:
    build: 
      context: .
      dockerfile: ./Dockerfile.celery
    env_file: .env
    command: celery -A celery_worker.celeryApp worker --loglevel=info --pool=solo --concurrency=1
    depends_on:
      - ocr-service
      - redis
    volumes:
      - ~/.cache/huggingface:/home/appuser/.cache/huggingface
    # deploy:
    #   replicas: 2
    environment:
      - REDIS_URL_OCR
      - REDIS_URL_CELERY
      - AWS_REGION
      - EXECUTION_QUEUE_URL
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY

  celery-flower:
    build: .
    command: celery -A celery_worker.celeryApp flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - celery-worker
    env_file: .env

  # Code execution workers for different languages
  java-executor:
    build: ./executors/java
    env_file: .env
    environment:
      - REDIS_URL_OCR
      - REDIS_URL_CELERY
      - AWS_REGION
      - EXECUTION_QUEUE_URL
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    depends_on:
      - redis
    # deploy:
    #   replicas: 2

  python-executor:
    build: ./executors/python
    env_file: .env
    environment:
      - REDIS_URL_OCR
      - REDIS_URL_CELERY
      - AWS_REGION
      - EXECUTION_QUEUE_URL
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    depends_on:
      - redis
    # deploy:
    #   replicas: 2

  javascript-executor:
    build: ./executors/javascript
    env_file: .env
    environment:
      - REDIS_URL_OCR
      - REDIS_URL_CELERY
      - AWS_REGION
      - EXECUTION_QUEUE_URL
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    depends_on:
      - redis
    # deploy:
    #   replicas: 2

  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - ocr-service

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
#   huggingface_cache:
#     driver: local
  redis_data: